apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-root
  annotations:
    cdi.kubevirt.io/storage.checkStaticVolume: ""
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 7Gi
    storageClassName: ocs-external-storagecluster-ceph-rbd
    volumeMode: Block
  source:
    registry:
      url: "docker://quay.io/kubevirtci/fedora-with-test-tooling:fc35-2208011009"
      pullMethod: node
